[package]
name = "powdr-backend"
description = "powdr backend types and API"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[features]
halo2 = ["dep:powdr-halo2"]
estark-polygon = ["dep:pil-stark-prover"]

[dependencies]
powdr-ast = { path = "../ast" }
powdr-halo2 = { path = "../halo2", optional = true }
powdr-number = { path = "../number" }
powdr-pil-analyzer = { path = "../pil-analyzer" }
powdr-executor = { path = "../executor" }

strum = { version = "0.24.1", features = ["derive"] }
log = "0.4.17"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0.43"
# TODO: use mainline repo once PR #252 is merged
starky = { git = "https://github.com/powdr-labs/eigen-zkvm.git", rev = "fcec08afc765e3259a8c8" }
pil-stark-prover = { git = "https://github.com/powdr-labs/pil-stark-prover.git", rev = "f0c7800564f78ed9414640317e905a777f43fd90", optional = true }
mktemp = "0.5.0"

[dev-dependencies]
test-log = "0.2.12"
env_logger = "0.10.0"
pretty_assertions = "1.4.0"

[package.metadata.cargo-udeps.ignore]
development = ["env_logger"]
